{% set name = "rattler-build" %}
{% set version = "0.76.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/prefix-dev/rattler-build/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2caad9c21e3293b04ff007f883ab42f465c8e619b230baffcd2a9d88a0979071

build:
  number: 0
  script:
    - export CARGO_PROFILE_RELEASE_STRIP=symbols
    # cmake is required by aws-lc-sys when CFLAGS inject -O2 (overrides -O0 in jitterentropy)
    - export AWS_LC_SYS_CMAKE_BUILDER=1
    - export CARGO_PROFILE_RELEASE_LTO=fat   # [osx and arm64]
    - export CARGO_PROFILE_RELEASE_LTO=thin  # [not (osx and arm64)]
    - export JEMALLOC_SYS_WITH_LG_PAGE=16    # [aarch64]
    - export OPENSSL_DIR="$PREFIX"  # [unix]
    - cargo auditable install --locked --no-default-features --features native-tls,recipe-generation,s3,sigstore,performance --bin rattler-build --root ${PREFIX} --path . --no-track  # [unix]
    - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml  # [unix]
    - mkdir -p $PREFIX/share/zsh/site-functions  # [unix]
    - $PREFIX/bin/rattler-build completion --shell zsh > $PREFIX/share/zsh/site-functions/_rattler-build  # [unix]
    - mkdir -p $PREFIX/share/bash-completion/completions  # [unix]
    - $PREFIX/bin/rattler-build completion --shell bash > $PREFIX/share/bash-completion/completions/rattler-build  # [unix]
    - mkdir -p $PREFIX/share/fish/vendor_completions.d  # [unix]
    - $PREFIX/bin/rattler-build completion --shell fish > $PREFIX/share/fish/vendor_completions.d/rattler-build.fish  # [unix]
    # path too long for pixi_config subpackage, https://github.com/prefix-dev/pixi/issues/3691
    - set CARGO_HOME=C:\.cargo  # [win]
    - md %CARGO_HOME%  # [win]
    - cargo auditable install --locked --no-default-features --features native-tls,recipe-generation,s3,sigstore,performance --bin rattler-build --root %PREFIX% --path . --no-track  # [win]
    - cargo-bundle-licenses --format yaml --output %SRC_DIR%/THIRDPARTY.yml  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - openssl {{ openssl }}  # [linux]
  run:
    - patchelf  # [linux]

test:
  files:
    - test-recipe
  commands:
    - rattler-build --help
    - test ! -f ${PREFIX}/bin/generate-cli-docs  # [unix]
    - test -f $PREFIX/share/zsh/site-functions/_rattler-build  # [unix]
    - test -f $PREFIX/share/bash-completion/completions/rattler-build  # [unix]
    - test -f $PREFIX/share/fish/vendor_completions.d/rattler-build.fish  # [unix]
    # check that we can fetch the sourcecode for slepc
    - rattler-build build --recipe ./test-recipe/check.yaml  # [unix]
    - rattler-build build --recipe ./test-recipe/check.yaml --output-dir %PREFIX%/out  # [win]

about:
  home: https://github.com/prefix-dev/rattler-build
  dev_url: https://github.com/prefix-dev/rattler-build
  doc_url: https://rattler.build
  summary: rattler-build is the universal conda package builder for Windows, macOS and Linux
  description: |
    The rattler-build tooling and library creates cross-platform relocatable binaries / packages
    from a simple recipe format.
    The recipe format is heavily inspired by conda-build and boa, and the output of a regular
    rattler-build run is a package that can be installed using mamba, conda or rattler.
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
    - CONDA_BUILD_LICENSE.txt
  license_family: BSD
